### ISSUE TITLE
white list related refactor

### ISSUE THREAD

**Issue by wu-cl** [everoute/everoute#311]
- [x] add endpoint type for static ip #305
- [x] add empty applyTo in security policy #307
- [x] add default type for security policy #306
- [x] create static endpoint from system endpoint #315 
- [x] agent add host manage IP at startup #322 
- [x] create sp for internal whitelist #320 
- [x] create sp for external whitelist - wait for tower schema #321 
- [x] remove whitelist in global policy #323
